### ISSUE TITLE
Create example application and library using CommonCrawl data

### ISSUE THREAD

**Issue by mikewalch** [fluo-io/fluo#32]
Currently, there is a [phrasecount](https://github.com/keith-turner/phrasecount) example for Accismus.  While phrasecount is helpful in learning Accismus, it would be great to have an example app based on more complicated, real world data like a corpus of crawled web data.  [CommonCrawl](http://commoncrawl.org) provides this data free via AWS. 

Create a library for loading CommonCrawl data into Accismus that could be used by developers learning Accismus.  Next, create an example application that analyzes the common crawl using Accismus using the library.  

This library and example app could also be used to stress Accismus using real-world data.

**Comment by keith-turner** [comment]
Done see https://github.com/fluo-io/webindex
