### ISSUE TITLE
Format code using Google style and enforce using Maven checkstyle plugin

### ISSUE THREAD

**Issue by mikewalch** [fluo-io/fluo#479]
Google style guide: 
https://code.google.com/p/google-styleguide/

Google check style:
http://checkstyle.sourceforge.net/google_style.html

**Comment by ctubbsii** [comment]
The project [revelc/apilyzer-maven-plugin][1] uses the Google style, if you want to check out that POM. The one annoying part is the imports ordering is a bit broken (see checkstyle/checkstyle#941). You can satisfy the check with the right Eclipse configuration, but it's not correct according to the style guide description.

[1]: http://github.com/revelc/apilyzer-maven-plugin
