### ISSUE TITLE
Make mini-fluo start wait

### ISSUE THREAD

**Issue by keith-turner** [fluo-io/fluo#505]
The mini fluo start command should probably wait until the client.properties file exist.   I had to do the following in a script trying to use `mini-fluo start`.

```bash
CLIENT_PROPS=$FLUO_HOME/apps/phrasecount/mini/client.properties

while [ ! -f $CLIENT_PROPS ]
do
  echo "Waiting for $CLIENT_PROPS to be created"
  sleep 1
done

```

**Comment by mikewalch** [comment]
Closed by #509
