### ISSUE TITLE
Make Oracle run on a random port

### ISSUE THREAD

**Issue by mikewalch** [fluo-io/fluo#518]
Currently, the oracle defaults to a well-known port (9913).  This becomes an issue when running multiple Fluo applications on a cluster as each run their own Oracle.

It would be better if the Oracle chose a random port and the configuration property that sets the port was removed as clients already discover how to connect to Oracle using zookeeper (for Oracle failover).

**Comment by GigabyteProductions** [comment]
Random ports causes issues when firewalling. This should be documented in default config file.

**Comment by kpm1985** [comment]
I presume you are referencing these lines:
https://github.com/apache/fluo/blob/01fc804f5914e6f9f2f4bfed8fc6e3e2701c16dd/modules/core/src/main/java/org/apache/fluo/core/oracle/OracleServer.java#L283-L289

We could add some documentation here warning the user that if it is not set it will default to a random free port here:
https://github.com/apache/fluo/blob/01fc804f5914e6f9f2f4bfed8fc6e3e2701c16dd/modules/core/src/main/java/org/apache/fluo/core/impl/FluoConfigurationImpl.java#L29-L30

@GigabyteProductions would you like to add a javadoc for this?

**Comment by mikewalch** [comment]
I agree that there should be better documentation about ports. While the Oracle chooses a random port by default, it can be set to use a fixed port by setting the property `fluo.impl.oracle.port`.

**Comment by GigabyteProductions** [comment]
@kpm1985 Yep. Those are the lines/config.

I'm not entirely sure how exactly you mean to add a javadoc. I did notice that this setting has no constants or functions in the public API side of things: https://static.javadoc.io/org.apache.fluo/fluo-api/1.2.0/org/apache/fluo/api/config/FluoConfiguration.html

@mikewalch Yep. That was the fix that I think should end up in a comment in the default config.

**Comment by GigabyteProductions** [comment]
... or possibly become in the (uncommented) default config, depending on anticipated use case (multiple oracles vs one oracle).
