### ISSUE TITLE
Create parent pom that can be shared by all Fluo projects

### ISSUE THREAD

**Issue by mikewalch** [fluo-io/fluo#546]
The main Fluo repo has Maven configuration for a lot of plugins that could be used by other project in the fluo-io like Java autoformat, checkstyle, etc.  It would be great to create a Maven parent pom for fluo-io that is shared by all projects.

**Comment by keith-turner** [comment]
Where are you thinking of putting this?  In its own github repo?  I suppose it will need to be released inorder to use it?

**Comment by mikewalch** [comment]
Yes.  I think it should be in its own github repo like https://github.com/revelc/revelc

**Comment by mikewalch** [comment]
@ctubbsii created a [repo][1] for the Fluo-io parent pom and modifed Fluo to use it in #613 

[1]: https://github.com/fluo-io/fluo-io-parent
